In [1]:
import pandas as pd
import numpy as np
from PIL import Image
import re

In [3]:
path_labels = np.load(r'D:\jupyter\Diploma\attr_img_new_shorted.npy',allow_pickle=True)
df = pd.DataFrame(path_labels, columns=['path','label'])

In [4]:
dict_df = pd.read_csv(r'D:\jupyter\Diploma\attr_cloth.csv',sep=';')

In [20]:
df.tail(10)

,path,label
289212,C:/Users/USRx/Desktop/Daria/img_highres/Paisle...,"139,275,624,625,681,682,730"
289213,C:/Users/USRx/Desktop/Daria/img_highres/Paisle...,"30,302,310,745,920"
289214,C:/Users/USRx/Desktop/Daria/img_highres/Paisle...,"30,681,682,730,745"
289215,C:/Users/USRx/Desktop/Daria/img_highres/Paisle...,"681,730,825"
289216,C:/Users/USRx/Desktop/Daria/img_highres/Paisle...,159
289217,C:/Users/USRx/Desktop/Daria/img_highres/Paisle...,"30,681,682,730"
289218,C:/Users/USRx/Desktop/Daria/img_highres/Paisle...,"275,681"
289219,C:/Users/USRx/Desktop/Daria/img_highres/Paisle...,"30,681"
289220,C:/Users/USRx/Desktop/Daria/img_highres/Paisle...,"30,681,682,730"
289221,C:/Users/USRx/Desktop/Daria/img_highres/Paisle...,"30,681,760,880"

In [1313]:
""" search_number = 1000
for i in range(15000, df.shape[0]):
    list_my = list(map(int, df.loc[i,'label'].split(',')))
    if search_number in list_my:
        print(i)
        print(dict_df.iloc[list_my])
        break """

15000
     english  russian
1000   empty  пропуск

In [26]:
delete_attr_list = dict_df[dict_df['russian']=='пропуск']
delete_attr_list = delete_attr_list.index.tolist()
delete_attr_list = [str(number) for number in delete_attr_list]
delete_attr_list[-50:-40]

['673', '675', '677', '679', '682', '684', '686', '705', '709', '714']

In [21]:
for i in range(df.shape[0]):
    new_list = []
    list = df.loc[i,'label'].split(',')
    for item in list:
        if item not in delete_attr_list:
            new_list.append(item)
    df.loc[i,'label'] = ','.join(new_list)
df.tail()

                                                     path           label
289217  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...      30,681,730
289218  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...         275,681
289219  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...          30,681
289220  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...      30,681,730
289221  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...  30,681,760,880

In [22]:
df.tail(10)

                                                     path                label
289212  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...  139,275,624,681,730
289213  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...   30,302,310,745,920
289214  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...       30,681,730,745
289215  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...              681,730
289216  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...                  159
289217  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...           30,681,730
289218  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...              275,681
289219  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...               30,681
289220  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...           30,681,730
289221  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...       30,681,760,880

In [6]:
df['label'] = df['label'].replace('', '1000')
df[df['label'].str.contains('1000')]

                                                     path label
10      C:/Users/USRx/Desktop/Daria/img_highres/Sheer_...  1000
41      C:/Users/USRx/Desktop/Daria/img_highres/Sheer_...  1000
51      C:/Users/USRx/Desktop/Daria/img_highres/Sheer_...  1000
62      C:/Users/USRx/Desktop/Daria/img_highres/Sheer_...  1000
73      C:/Users/USRx/Desktop/Daria/img_highres/Sheer_...  1000
...                                                   ...   ...
288862  C:/Users/USRx/Desktop/Daria/img_highres/Cutout...  1000
288948  C:/Users/USRx/Desktop/Daria/img_highres/Cutout...  1000
288959  C:/Users/USRx/Desktop/Daria/img_highres/Cutout...  1000
289131  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...  1000
289132  C:/Users/USRx/Desktop/Daria/img_highres/Paisle...  1000

[14019 rows x 2 columns]

In [7]:
df = df.to_numpy()
np.save(r'D:\jupyter\Diploma\FinalFolder\attr_img_shorted_delattr.npy',df)